<a href="https://colab.research.google.com/github/Mat9408/Atividades_CursoAnalistaDeDados_EBAC/blob/main/M%C3%B3dulo_12_Tarefa_completa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from bs4 import BeautifulSoup

pagina = BeautifulSoup(open('fortune.html', mode= 'r'), 'html.parser')

In [ ]:
# extraindo as linhas da tabela

tabela = pagina.find('div', {'class': 'rt-table'})
linhas = tabela.find('div', {'class': 'rt-tbody'})

In [ ]:
# extrair o conteudo das linhas da tabela

lista_dados = []

for linha in linhas:
    colunas = linha.find('div', {'role': 'row'})
    colunas = colunas.get_text(separator=';').split(';')
    lista_dados.append(colunas)
print(lista_dados)

[['1', 'Walmart', '$559,151', '6.7%', '$13,510', '-9.2%', '$252,496', '$382,642.8', '2,300,000'], ['2', 'Amazon', '$386,064', '37.6%', '$21,331', '84.1%', '$321,195', '$1,558,069.6', '1,298,000'], ['3', 'Apple', '$274,515', '5.5%', '$57,411', '3.9%', '$323,888', '$2,050,665.9', '147,000'], ['4', 'CVS Health', '$268,706', '4.6%', '$7,179', '8.2%', '$230,715', '$98,653.2', '256,500'], ['5', 'UnitedHealth Group', '$257,141', '6.2%', '$15,403', '11.3%', '$197,289', '$351,725', '330,000'], ['6', 'Berkshire Hathaway', '$245,510', '-3.6%', '$42,521', '-47.8%', '$873,729', '$587,823', '360,000'], ['7', 'McKesson', '$231,051', '7.8%', '$900', '2547.1%', '$61,247', '$31,044', '70,000'], ['8', 'AmerisourceBergen', '$189,893.9', '5.7%', '$-3,408.7', '-498.5%', '$44,274.8', '$24,169.7', '21,500'], ['9', 'Alphabet', '$182,527', '12.8%', '$40,269', '17.3%', '$319,616', '$1,392,561.8', '135,301'], ['10', 'Exxon Mobil', '$181,502', '-31.5%', '$-22,440', '-256.5%', '$332,750', '$236,355.4', '72,000'], ['11', 'AT&T', '$171,760', '-5.2%', '$-5,176', '-137.2%', '$525,761', '$215,878.5', '230,760'], ['12', 'Costco Wholesale', '$166,761', '9.2%', '$4,002', '9.4%', '$55,556', '$155,984.3', '214,500'], ['13', 'Cigna', '$160,401', '4.5%', '$8,458', '65.7%', '$155,451', '$83,976.1', '72,963'], ['14', 'Cardinal Health', '$152,922', '5.1%', '$-3,696', '-371.2%', '$40,766', '$17,840.3', '48,000'], ['15', 'Microsoft', '$143,015', '13.6%', '$44,281', '12.8%', '$301,311', '$1,778,228.2', '163,000'], ['16', 'Walgreens Boots Alliance', '$139,537', '2%', '$456', '-88.5%', '$87,174', '$47,455.3', '277,000'], ['17', 'Kroger', '$132,498', '8.4%', '$2,585', '55.8%', '$48,662', '$27,064.3', '465,000'], ['18', 'Home Depot', '$132,110', '19.9%', '$12,866', '14.4%', '$70,581', '$328,775.4', '504,800'], ['19', 'JPMorgan Chase', '$129,503', '-9.1%', '$29,131', '-20%', '$3,386,071', '$464,530.8', '255,351'], ['20', 'Verizon Communications', '$128,292', '-2.7%', '$17,801', '-7.6%', '$316,481', '$240,633.3', '132,200'], ['21', 'Ford Motor', '$127,144', '-18.4%', '$-1,279', '-2821.3%', '$267,261', '$48,739', '186,000'], ['22', 'General Motors', '$122,485', '-10.7%', '$6,427', '-4.5%', '$235,194', '$82,794.9', '155,000'], ['23', 'Anthem', '$121,867', '16.9%', '$4,572', '-4.9%', '$86,615', '$87,908.9', '83,400'], ['24', 'Centene', '$111,115', '48.9%', '$1,808', '36.9%', '$68,719', '$37,169.6', '71,300'], ['25', 'Fannie Mae', '$106,437', '-11.5%', '$11,805', '-16.6%', '$3,985,749', '$2,397.2', '7,700'], ['26', 'Comcast', '$103,564', '-4.9%', '$10,534', '-19.3%', '$273,869', '$247,859.3', '168,000'], ['27', 'Chevron', '$94,692', '-35.4%', '$-5,543', '-289.6%', '$239,790', '$201,865', '47,736'], ['28', 'Dell Technologies', '$94,224', '2.2%', '$3,250', '-29.6%', '$123,415', '$67,229.1', '158,000'], ['29', 'Bank of America', '$93,753', '-17.5%', '$17,894', '-34.8%', '$2,819,627', '$333,788.4', '212,505'], ['30', 'Target', '$93,561', '19.8%', '$4,368', '33.1%', '$51,248', '$98,760.9', '409,000'], ['31', "Lowe's", '$89,597', '24.2%', '$5,835', '36.3%', '$46,735', '$136,407.9', '280,000'], ['32', 'Marathon Petroleum', '$88,952', '-28.7%', '$-9,826', '-472.6%', '$85,158', '$34,873.8', '57,900'], ['33', 'Citigroup', '$88,839', '-14.1%', '$11,047', '-43.1%', '$2,260,090', '$151,806.4', '210,153'], ['34', 'Facebook', '$85,965', '21.6%', '$29,146', '57.7%', '$159,316', '$838,724.2', '58,604'], ['35', 'UPS', '$84,628', '14.2%', '$1,343', '-69.8%', '$62,408', '$147,791.6', '408,255'], ['36', 'Johnson & Johnson', '$82,584', '0.6%', '$14,714', '-2.7%', '$174,894', '$432,685.3', '134,500'], ['37', 'Wells Fargo', '$80,303', '-22.7%', '$3,301', '-83.1%', '$1,955,163', '$161,521', '268,531'], ['38', 'General Electric', '$79,619', '-16.4%', '$5,704', '-', '$253,452', '$115,342.5', '184,000'], ['39', 'State Farm Insurance', '$78,898', '-0.6%', '$3,738.9', '-33.1%', '$299,104.5', '-', '57,582'], ['40', 'Intel', '$77,867', '8.2%', '$20,899', '-0.7%', '$153,091', '$260,630.1', '110,600'], ['41', 'Humana', '$77,155', '18.9%', '$3,367', '24.4%', '$34,969', '$54,087.7', '48,700'], ['42', 'IBM', '$73,620', '-4.6%', '$5,590', '-40.7%', '$155,971', '$119,080.3', '364,800'], ['43', 'Procter & Gamble', '$70,950', '4.8%', '$13,027', '234.3%', '$120,700', '$333,493.1', '99,000'], ['44', 'PepsiCo', '$70,372', '4.8%', '$7,120', '-2.7%', '$92,918', '$195,207.7', '291,000'], ['45', 'FedEx', '$69,217', '-0.7%', '$1,286', '138.1%', '$73,537', '$75,367.8', '418,000'], ['46', 'MetLife', '$67,842', '-2.6%', '$5,407', '-8.3%', '$795,146', '$53,762.6', '46,500'], ['47', 'Freddie Mac', '$66,228', '-11.8%', '$7,326', '1.6%', '$2,627,415', '$1,332.6', '6,922'], ['48', 'Phillips 66', '$65,494', '-40.2%', '$-3,975', '-229.2%', '$54,721', '$35,703.6', '14,300'], ['49', 'Lockheed Martin', '$65,398', '9.3%', '$6,833', '9.7%', '$50,710', '$102,984.2', '114,000'], ['50', 'Walt Disney', '$65,388', '-6%', '$-2,864', '-125.9%', '$201,549', '$334,952.5', '203,000'], ['51', 'Archer Daniels Midland', '$64,355', '-0.5%', '$1,772', '28.5%', '$49,719', '$31,834.5', '38,332'], ['52', 'Albertsons', '$62,455.1', '3.2%', '$466.4', '255.8%', '$24,735.1', '$8,877.7', '270,000'], ['53', 'Valero Energy', '$60,115', '-41.5%', '$-1,421', '-158.7%', '$51,774', '$29,267.2', '9,964'], ['54', 'Boeing', '$58,158', '-24%', '$-11,873', '-', '$152,136', '$148,664.8', '141,000'], ['55', 'Prudential Financial', '$57,033', '-12%', '$-374', '-108.9%', '$940,722', '$36,022.4', '41,671'], ['56', 'HP', '$56,639', '-3.6%', '$2,844', '-9.8%', '$34,681', '$39,579.5', '53,000'], ['57', 'Raytheon Technologies', '$56,587', '-26.6%', '$-3,519', '-163.6%', '$162,153', '$117,143.9', '181,000'], ['58', 'StoneX Group', '$54,139.6', '64.6%', '$169.6', '99.3%', '$13,474.9', '$1,284.4', '2,950'], ['59', 'Goldman Sachs Group', '$53,498', '-0.8%', '$9,459', '11.7%', '$1,163,028', '$116,903', '40,500'], ['60', 'Sysco', '$52,893.3', '-12%', '$215.5', '-87.1%', '$22,628.3', '$40,189.8', '57,000'], ['61', 'Morgan Stanley', '$52,047', '-3.3%', '$10,996', '21.6%', '$1,115,862', '$146,161.9', '68,097'], ['62', 'HCA Healthcare', '$51,533', '0.4%', '$3,754', '7.1%', '$47,490', '$63,458.7', '235,000'], ['63', 'Cisco Systems', '$49,301', '-5%', '$11,214', '-3.5%', '$94,853', '$218,308.5', '77,500'], ['64', 'Charter Communications', '$48,097', '5.1%', '$3,222', '93.2%', '$144,206', '$128,965.7', '96,100'], ['65', 'Merck', '$47,994', '2.5%', '$7,067', '-28.2%', '$91,588', '$195,062', '73,500'], ['66', 'Best Buy', '$47,262', '8.3%', '$1,798', '16.7%', '$19,067', '$28,707.7', '81,600'], ['67', 'New York Life Insurance', '$46,712.4', '5.9%', '$-822.3', '-181.9%', '$359,312.5', '-', '11,506'], ['68', 'AbbVie', '$45,804', '37.7%', '$4,616', '-41.4%', '$150,565', '$190,989.4', '47,000'], ['69', 'Publix Super Markets', '$45,204', '17.5%', '$3,971.8', '32.2%', '$28,094.1', '-', '227,000'], ['70', 'Allstate', '$44,791', '0.3%', '$5,576', '15%', '$125,987', '$34,800.2', '42,010'], ['71', 'Liberty Mutual Insurance Group', '$43,796', '1.3%', '$758', '-27.4%', '$145,377', '-', '45,000'], ['72', 'AIG', '$43,736', '-12.1%', '$-5,944', '-277.5%', '$586,481', '$39,848.9', '45,000'], ['73', 'Tyson Foods', '$43,185', '1.8%', '$2,061', '4.1%', '$34,456', '$27,099.6', '139,000'], ['74', 'Progressive', '$42,658.1', '9.3%', '$5,704.6', '43.7%', '$64,098.3', '$55,946.5', '43,326'], ['75', 'Bristol-Myers Squibb', '$42,518', '62.6%', '$-9,015', '-362.1%', '$118,481', '$141,027.9', '30,250'], ['76', 'Nationwide', '$41,929.8', '-4.7%', '$-138.4', '-116.7%', '$256,589.3', '-', '25,391'], ['77', 'Pfizer', '$41,908', '-19%', '$9,616', '-40.9%', '$154,229', '$202,096.9', '78,500'], ['78', 'Caterpillar', '$41,748', '-22.4%', '$2,998', '-50.8%', '$78,324', '$126,439.6', '97,300'], ['79', 'TIAA', '$41,619.3', '2.9%', '$558.1', '-77.3%', '$654,252', '-', '14,953'], ['80', 'Oracle', '$39,068', '-1.1%', '$10,135', '-8.6%', '$115,438', '$202,337.7', '135,000'], ['81', 'Energy Transfer', '$38,954', '-28.1%', '$-648', '-118%', '$95,144', '$20,754.7', '11,421'], ['82', 'Dow', '$38,542', '-10.3%', '$1,225', '-', '$61,470', '$47,649.7', '35,700'], ['83', 'American Express', '$38,185', '-18.8%', '$3,135', '-53.6%', '$191,367', '$113,635.8', '63,700'], ['84', 'General Dynamics', '$37,925', '-3.6%', '$3,167', '-9.1%', '$51,308', '$51,481.9', '100,700'], ['85', 'Nike', '$37,403', '-4.4%', '$2,539', '-37%', '$31,342', '$209,499.8', '75,400'], ['86', 'Northrop Grumman', '$36,799', '8.7%', '$3,189', '41.9%', '$44,469', '$53,956.7', '97,000'], ['87', 'USAA', '$36,296.2', '1.9%', '$3,906.9', '-2.5%', '$200,348.4', '-', '35,935'], ['88', 'Deere', '$35,540', '-9.5%', '$2,751', '-15.4%', '$75,091', '$117,270', '69,634'], ['89', 'Abbott Laboratories', '$34,608', '8.5%', '$4,495', '21.9%', '$72,548', '$212,300.1', '109,000'], ['90', 'Northwestern Mutual', '$33,782.1', '4.6%', '$425', '-66.5%', '$308,767', '-', '6,641'], ['91', 'Dollar General', '$33,746.8', '21.6%', '$2,655.1', '55%', '$25,862.6', '$48,479.7', '158,000'], ['92', 'Exelon', '$33,039', '-4.1%', '$1,963', '-33.1%', '$129,317', '$42,723.5', '32,340'], ['93', 'Coca-Cola', '$33,014', '-11.4%', '$7,747', '-13.2%', '$87,296', '$227,143.8', '80,300'], ['94', 'Honeywell International', '$32,637', '-11.1%', '$4,779', '-22.2%', '$64,586', '$150,972.4', '103,000'], ['95', 'Thermo Fisher Scientific', '$32,218', '26.1%', '$6,375', '72.5%', '$69,052', '$179,719.4', '84,362'], ['96', '3M', '$32,184', '0.1%', '$5,384', '17.8%', '$47,344', '$111,642.1', '94,987'], ['97', 'TJX', '$32,137', '-23%', '$90.5', '-97.2%', '$30,813.6', '$79,774.9', '320,000'], ['98', 'Travelers', '$31,981', '1.3%', '$2,697', '2.9%', '$116,764', '$37,933', '30,294'], ['99', 'Capital One Financial', '$31,643', '-6.3%', '$2,714', '-51.1%', '$421,602', '$58,097', '51,985'], ['100', 'Tesla', '$31,536', '28.3%', '$721', '-', '$52,148', '$641,115', '70,757']]

In [ ]:
header = [ 'rank',
           'name',
           'revenues',
           'revenues-percent-change',
           'profits',
           'profits-percent-change',
           'assets',
           'mark-value',
           'employees'
]

In [ ]:
# escrever todas as informações extraídas para o arquivo fortune.csv

import csv

with open(file='./fortune.csv', mode='w', encoding='utf-8') as fp:
  escritor_csv = csv.writer(fp, delimiter= ',')
  escritor_csv.writerows([header] + lista_dados)

In [ ]:
# Criando o DataFrame

import pandas as pd

fortune_df = pd.read_csv('fortune.csv', sep=',')

In [ ]:
fortune_df

,rank,name,revenues,revenues-percent-change,profits,profits-percent-change,assets,mark-value,employees
0,1,Walmart,"$559,151",6.7%,"$13,510",-9.2%,"$252,496","$382,642.8","2,300,000"
1,2,Amazon,"$386,064",37.6%,"$21,331",84.1%,"$321,195","$1,558,069.6","1,298,000"
2,3,Apple,"$274,515",5.5%,"$57,411",3.9%,"$323,888","$2,050,665.9","147,000"
3,4,CVS Health,"$268,706",4.6%,"$7,179",8.2%,"$230,715","$98,653.2","256,500"
4,5,UnitedHealth Group,"$257,141",6.2%,"$15,403",11.3%,"$197,289","$351,725","330,000"
...,...,...,...,...,...,...,...,...,...
95,96,3M,"$32,184",0.1%,"$5,384",17.8%,"$47,344","$111,642.1","94,987"
96,97,TJX,"$32,137",-23%,$90.5,-97.2%,"$30,813.6","$79,774.9","320,000"
97,98,Travelers,"$31,981",1.3%,"$2,697",2.9%,"$116,764","$37,933","30,294"
98,99,Capital One Financial,"$31,643",-6.3%,"$2,714",-51.1%,"$421,602","$58,097","51,985"
99,100,Tesla,"$31,536",28.3%,$721,-,"$52,148","$641,115","70,757"

In [ ]:
# Explorando o DataFrame

# - Liste as 10 primeiras linhas do DataFrame:
fortune_df.head(10)

,rank,name,revenues,revenues-percent-change,profits,profits-percent-change,assets,mark-value,employees
0,1,Walmart,"$559,151",6.7%,"$13,510",-9.2%,"$252,496","$382,642.8","2,300,000"
1,2,Amazon,"$386,064",37.6%,"$21,331",84.1%,"$321,195","$1,558,069.6","1,298,000"
2,3,Apple,"$274,515",5.5%,"$57,411",3.9%,"$323,888","$2,050,665.9","147,000"
3,4,CVS Health,"$268,706",4.6%,"$7,179",8.2%,"$230,715","$98,653.2","256,500"
4,5,UnitedHealth Group,"$257,141",6.2%,"$15,403",11.3%,"$197,289","$351,725","330,000"
5,6,Berkshire Hathaway,"$245,510",-3.6%,"$42,521",-47.8%,"$873,729","$587,823","360,000"
6,7,McKesson,"$231,051",7.8%,$900,2547.1%,"$61,247","$31,044","70,000"
7,8,AmerisourceBergen,"$189,893.9",5.7%,"$-3,408.7",-498.5%,"$44,274.8","$24,169.7","21,500"
8,9,Alphabet,"$182,527",12.8%,"$40,269",17.3%,"$319,616","$1,392,561.8","135,301"
9,10,Exxon Mobil,"$181,502",-31.5%,"$-22,440",-256.5%,"$332,750","$236,355.4","72,000"

In [ ]:
# - Liste os tipos de dados armazenados na coluna do DataFrame:

fortune_df.dtypes

rank                        int64
name                       object
revenues                   object
revenues-percent-change    object
profits                    object
profits-percent-change     object
assets                     object
mark-value                 object
employees                  object
dtype: object

In [ ]:
# - Liste o número de linhas e colunas do DataFrame:

fortune_df.shape

(100, 9)

In [ ]:
# Limpando o DataFrame:

fortune_df['revenues'] = fortune_df['revenues'].apply(lambda x: x.replace('$','') if "$" in x else x)
fortune_df['revenues-percent-change'] = fortune_df['revenues-percent-change'].apply(lambda x: x.replace('%','') if "%" in x else x)
fortune_df['profits'] = fortune_df['profits'].apply(lambda x: x.replace('$','') if "$" in x else x)
fortune_df['profits-percent-change'] = fortune_df['profits-percent-change'].apply(lambda x: x.replace('%','') if "%" in x else x)
fortune_df['assets'] = fortune_df['assets'].apply(lambda x: x.replace('$','') if "$" in x else x)
fortune_df['mark-value'] = fortune_df['mark-value'].apply(lambda x: x.replace('$','') if "$" in x else x)

In [ ]:
fortune_df

,rank,name,revenues,revenues-percent-change,profits,profits-percent-change,assets,mark-value,employees
0,1,Walmart,"559,151",6.7,"13,510",-9.2,"252,496","382,642.8","2,300,000"
1,2,Amazon,"386,064",37.6,"21,331",84.1,"321,195","1,558,069.6","1,298,000"
2,3,Apple,"274,515",5.5,"57,411",3.9,"323,888","2,050,665.9","147,000"
3,4,CVS Health,"268,706",4.6,"7,179",8.2,"230,715","98,653.2","256,500"
4,5,UnitedHealth Group,"257,141",6.2,"15,403",11.3,"197,289","351,725","330,000"
...,...,...,...,...,...,...,...,...,...
95,96,3M,"32,184",0.1,"5,384",17.8,"47,344","111,642.1","94,987"
96,97,TJX,"32,137",-23,90.5,-97.2,"30,813.6","79,774.9","320,000"
97,98,Travelers,"31,981",1.3,"2,697",2.9,"116,764","37,933","30,294"
98,99,Capital One Financial,"31,643",-6.3,"2,714",-51.1,"421,602","58,097","51,985"
99,100,Tesla,"31,536",28.3,721,-,"52,148","641,115","70,757"

In [ ]:
fortune_df.to_csv('fortune-limpo.csv', encoding= 'utf-8')